services:
  athlete-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.sparkfly.cloud/athlefi/athlete-api:local-latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=athlete_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=athlete_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: